//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectMember
    {
        public string IDMember { get; set; }
        public string IDProject { get; set; }
        public string Works { get; set; }
        public Nullable<bool> Progress { get; set; }
        public string LinkCheckProgress { get; set; }
    
        public virtual Member Member { get; set; }
        public virtual Project Project { get; set; }
    }
}
